environment: development
appname: "publisher-service"
serviceport: 8080
db:
  host: "localhost"
  user: "postgres"
  name: "sales_analytics"
  password: "password"
  ssl_mode: "disable"
kafka:
  host: "localhost"
  port: "19092"